name: Build and Deploy .NET App

on:
  workflow_dispatch:

jobs:
  build-job:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .Net Core
        uses: actions/setup-dotnet@v4.2.0
        with:
          dotnet-version: '8.x'

      - name: Build Code
        run: dotnet build --configuration Release

      - name: Publish Code
        run: dotnet publish -c Release --property:PublishDir="${{ env.DOTNET_ROOT }}\myapp"
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.5.0
        with:
          name: .net-app
          path: ${{ env.DOTNET_ROOT }}\myapp

  deploy-job:
    runs-on: windows-latest
    needs: build-job
    env:
      package-name: .net-app
      app-name: azureapp1
      deployment-slot: production

    steps:
      - name: Download Artifact from build job
        uses: actions/download-artifact@v4.1.8
        with:
          name: ${{ env.package-name }}

      - name: Secret Information 
        run: echo "Value of secret matches ${{ secrets.AZURE_PUBLISH_PROFILE == 'Placeholder' }}"

      - name: Print name of App Service to deploy to
        run: echo "App will be deployed on ${{ env.app-name }}"

      - name: List files in root directory 
        run: |
          Get-ChildItem -Path . | ForEach-Object { Write-Output $_.Name }
        shell: pwsh
