name: butler

on:
  issue_comment:
    types: [created]

permissions: # Permissions on the level of the workflow
  pull-requests: write
jobs:
  chat:
    runs-on: ubuntu-latest

    steps:
      - uses: ca-dp/butler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          cmd: chat
          comment_body: ${{ github.event.comment.body }}

