name: cd-azure

on:
  push:
    paths:
      - '.github/workflows/cd-azure.yml'
      - 'api/**'
  workflow_dispatch:  # Manually trigger the workflow

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0 # All commits, so we can generate version off of tags/commit SHA...
        - uses: docker/setup-buildx-action@v3.8.0

        - run: docker buildx ls

        - uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}

        - run: ./build-push.sh  # Can reuse local build scripts for CI/CD
          working-directory: api