name: upper-capture

on:
  workflow_dispatch:

jobs:
  capture:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: upper

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.22
          cache-dependency-path: ./upper/go.sum

      - run: |
          ls
          go build
          ls
          go test -v

      - uses: actions/upload-artifact@v4
        with:
          path: ./upper/upper
          name: "build-${{ matrix.os }}"


