name: Issues Workflow
on:
  issues:
    types: [opened, assigned, labeled, closed]
  workflow_dispatch:

jobs:
  comment-on-issue:
    runs-on: ubuntu-latest
    permissions:  # check workflow permissions
        contents: read
        issues: write
    steps:
    - uses: actions/github-script@v7
      id: issue_script
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const issue_number = context.issue.number;
          console.log(`Issue Number: ${issue_number}`);
              
          //const owner = context.repo.owner;
          //const repo = context.repo.repo;
              
          // lookup issue info
          const issue = await github.rest.issues.get({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
         });
          
          console.log(`issue: ${issue}`);
          
          // add a comment to the issue
          
          const comment = await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            });
          
          console.log(`comment id: ${comment.data.id}`);
          console.log(comment.data);
          
          // add a label to the issue
            const label = await github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['todo-review']
            })
          
            // Make comment id available to subsequent steps
            return comment.data.id;

    - name: Get the comment id
      run: echo "Comment id is ${{ steps.issue_script.outputs.result }}"


          
          
              
