name: Issues Workflow
on:
  issues:
    types: [opened, assigned, labeled, closed]
  workflow_dispatch:

jobs:
  comment-on-issue:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        issues: write
    steps:
    - uses: actions/github-script@v7
      id: issue_script
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const issue_number = context.issue.number;
          console.log(`Issue Number: ${issue_number}`);
              
          const owner = context.repo.owner;
          const repo = context.repo.repo;
              
          // lookup issue info
          const issue = await github.issues.get({
           owner,
           repo,
           issue_number
          });
          
          console.log(`issue: ${issue}`);
          
          // add a comment to the issue
          
          const comment = await github.issues.createComment({
           owner,
           repo,
           issue_number,
           body: 'Thanks for your contribution!'
          });
          
          console.log(`comment id: ${comment.data.id}`);
          console.log(comment.data);
          
          // add a label to the issue
            const label = await github.issues.addLabels({
             owner,
             repo,
             issue_number,
             labels: ['todo-review']
            });
          
            // Make comment id available to subsequent steps
            return comment.data.id;

    - name: Get the comment id
      run: echo "Comment id is ${{ steps.issue_script.outputs.result }}"


          
          
              
